<?php
/**
 * AudienceGroupJobStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\ManageAudience
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LINE\Clients\ManageAudience\Model;
use \LINE\Clients\ManageAudience\ObjectSerializer;

/**
 * AudienceGroupJobStatus Class Doc Comment
 *
 * @category Class
 * @description Job status
 * @package  LINE\Clients\ManageAudience
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AudienceGroupJobStatus
{
    /**
     * Possible values of this enum
     */
    public const QUEUED = 'QUEUED';

    public const WORKING = 'WORKING';

    public const FINISHED = 'FINISHED';

    public const FAILED = 'FAILED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::QUEUED,
            self::WORKING,
            self::FINISHED,
            self::FAILED
        ];
    }
}


