<?php
/**
 * Copyright 2025 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/**
 * CreateAudienceGroupResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\ManageAudience
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LINE\Clients\ManageAudience\Model;

use \ArrayAccess;
use \LINE\Clients\ManageAudience\ObjectSerializer;

/**
 * CreateAudienceGroupResponse Class Doc Comment
 *
 * @category Class
 * @description Create audience for uploading user IDs (by JSON)
 * @package  LINE\Clients\ManageAudience
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateAudienceGroupResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateAudienceGroupResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'audienceGroupId' => 'int',
        'createRoute' => 'string',
        'type' => '\LINE\Clients\ManageAudience\Model\AudienceGroupType',
        'description' => 'string',
        'created' => 'int',
        'permission' => 'string',
        'expireTimestamp' => 'int',
        'isIfaAudience' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'audienceGroupId' => 'int64',
        'createRoute' => null,
        'type' => null,
        'description' => null,
        'created' => 'int64',
        'permission' => null,
        'expireTimestamp' => 'int64',
        'isIfaAudience' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'audienceGroupId' => false,
        'createRoute' => false,
        'type' => false,
        'description' => false,
        'created' => false,
        'permission' => false,
        'expireTimestamp' => false,
        'isIfaAudience' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'audienceGroupId' => 'audienceGroupId',
        'createRoute' => 'createRoute',
        'type' => 'type',
        'description' => 'description',
        'created' => 'created',
        'permission' => 'permission',
        'expireTimestamp' => 'expireTimestamp',
        'isIfaAudience' => 'isIfaAudience'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'audienceGroupId' => 'setAudienceGroupId',
        'createRoute' => 'setCreateRoute',
        'type' => 'setType',
        'description' => 'setDescription',
        'created' => 'setCreated',
        'permission' => 'setPermission',
        'expireTimestamp' => 'setExpireTimestamp',
        'isIfaAudience' => 'setIsIfaAudience'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'audienceGroupId' => 'getAudienceGroupId',
        'createRoute' => 'getCreateRoute',
        'type' => 'getType',
        'description' => 'getDescription',
        'created' => 'getCreated',
        'permission' => 'getPermission',
        'expireTimestamp' => 'getExpireTimestamp',
        'isIfaAudience' => 'getIsIfaAudience'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CREATE_ROUTE_MESSAGING_API = 'MESSAGING_API';
    public const PERMISSION_READ = 'READ';
    public const PERMISSION_READ_WRITE = 'READ_WRITE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCreateRouteAllowableValues()
    {
        return [
            self::CREATE_ROUTE_MESSAGING_API,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPermissionAllowableValues()
    {
        return [
            self::PERMISSION_READ,
            self::PERMISSION_READ_WRITE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('audienceGroupId', $data ?? [], null);
        $this->setIfExists('createRoute', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('permission', $data ?? [], null);
        $this->setIfExists('expireTimestamp', $data ?? [], null);
        $this->setIfExists('isIfaAudience', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCreateRouteAllowableValues();
        if (!is_null($this->container['createRoute']) && !in_array($this->container['createRoute'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'createRoute', must be one of '%s'",
                $this->container['createRoute'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPermissionAllowableValues();
        if (!is_null($this->container['permission']) && !in_array($this->container['permission'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'permission', must be one of '%s'",
                $this->container['permission'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets audienceGroupId
     *
     * @return int|null
     */
    public function getAudienceGroupId()
    {
        return $this->container['audienceGroupId'];
    }

    /**
     * Sets audienceGroupId
     *
     * @param int|null $audienceGroupId The audience ID.
     *
     * @return self
     */
    public function setAudienceGroupId($audienceGroupId)
    {
        if (is_null($audienceGroupId)) {
            throw new \InvalidArgumentException('non-nullable audienceGroupId cannot be null');
        }
        $this->container['audienceGroupId'] = $audienceGroupId;

        return $this;
    }

    /**
     * Gets createRoute
     *
     * @return string|null
     */
    public function getCreateRoute()
    {
        return $this->container['createRoute'];
    }

    /**
     * Sets createRoute
     *
     * @param string|null $createRoute How the audience was created.  `MESSAGING_API`: An audience created with Messaging API.
     *
     * @return self
     */
    public function setCreateRoute($createRoute)
    {
        if (is_null($createRoute)) {
            throw new \InvalidArgumentException('non-nullable createRoute cannot be null');
        }
        $allowedValues = $this->getCreateRouteAllowableValues();
        if (!in_array($createRoute, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'createRoute', must be one of '%s'",
                    $createRoute,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['createRoute'] = $createRoute;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \LINE\Clients\ManageAudience\Model\AudienceGroupType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \LINE\Clients\ManageAudience\Model\AudienceGroupType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The audience's name.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets created
     *
     * @return int|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param int|null $created When the audience was created (in UNIX time).
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets permission
     *
     * @return string|null
     */
    public function getPermission()
    {
        return $this->container['permission'];
    }

    /**
     * Sets permission
     *
     * @param string|null $permission Audience's update permission. Audiences linked to the same channel will be READ_WRITE.  `READ`: Can use only. `READ_WRITE`: Can use and update.
     *
     * @return self
     */
    public function setPermission($permission)
    {
        if (is_null($permission)) {
            throw new \InvalidArgumentException('non-nullable permission cannot be null');
        }
        $allowedValues = $this->getPermissionAllowableValues();
        if (!in_array($permission, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'permission', must be one of '%s'",
                    $permission,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['permission'] = $permission;

        return $this;
    }

    /**
     * Gets expireTimestamp
     *
     * @return int|null
     */
    public function getExpireTimestamp()
    {
        return $this->container['expireTimestamp'];
    }

    /**
     * Sets expireTimestamp
     *
     * @param int|null $expireTimestamp Time of audience expiration. Only returned for specific audiences.
     *
     * @return self
     */
    public function setExpireTimestamp($expireTimestamp)
    {
        if (is_null($expireTimestamp)) {
            throw new \InvalidArgumentException('non-nullable expireTimestamp cannot be null');
        }
        $this->container['expireTimestamp'] = $expireTimestamp;

        return $this;
    }

    /**
     * Gets isIfaAudience
     *
     * @return bool|null
     */
    public function getIsIfaAudience()
    {
        return $this->container['isIfaAudience'];
    }

    /**
     * Sets isIfaAudience
     *
     * @param bool|null $isIfaAudience The value indicating the type of account to be sent, as specified when creating the audience for uploading user IDs. One of:  `true`: Accounts are specified with IFAs. `false` (default): Accounts are specified with user IDs.
     *
     * @return self
     */
    public function setIsIfaAudience($isIfaAudience)
    {
        if (is_null($isIfaAudience)) {
            throw new \InvalidArgumentException('non-nullable isIfaAudience cannot be null');
        }
        $this->container['isIfaAudience'] = $isIfaAudience;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Create an instance of CreateAudienceGroupResponse from a dict (associative array)
     *
     * @internal This method is intended to be used internally only for now.
     *
     * @param array|null $data Associative array of property values
     * @return CreateAudienceGroupResponse
     */
    public static function fromAssocArray(?array $data): self
    {
        if ($data === null) {
            return new static();
        }

        $instance = new static();

        if (isset($data['audienceGroupId'])) {
            $instance->setaudienceGroupId($data['audienceGroupId']);
        }
        if (isset($data['createRoute'])) {
            $instance->setcreateRoute($data['createRoute']);
        }
        if (isset($data['type'])) {
            $instance->settype($data['type']);
        }
        if (isset($data['description'])) {
            $instance->setdescription($data['description']);
        }
        if (isset($data['created'])) {
            $instance->setcreated($data['created']);
        }
        if (isset($data['permission'])) {
            $instance->setpermission($data['permission']);
        }
        if (isset($data['expireTimestamp'])) {
            $instance->setexpireTimestamp($data['expireTimestamp']);
        }
        if (isset($data['isIfaAudience'])) {
            $instance->setisIfaAudience($data['isIfaAudience']);
        }

        return $instance;
    }
}


