<?php
/**
 * EventMode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LINE\Webhook\Model;
use \LINE\Webhook\ObjectSerializer;

/**
 * EventMode Class Doc Comment
 *
 * @category Class
 * @description Channel state.
 * @package  LINE\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventMode
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'active';

    public const STANDBY = 'standby';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::STANDBY
        ];
    }
}


