<?php
/**
 * GetAllLiffAppsResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\Liff
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LINE\Clients\Liff\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetAllLiffAppsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetAllLiffAppsResponse
 * @package     LINE\Clients\Liff
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetAllLiffAppsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetAllLiffAppsResponse"
     */
    public function testGetAllLiffAppsResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "apps"
     */
    public function testPropertyApps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
