<?php
/**
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/**
 * ChannelAccessTokenApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\ChannelAccessToken
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Channel Access Token API
 *
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LINE\Clients\ChannelAccessToken\Test\Api;

use \LINE\Clients\ChannelAccessToken\Configuration;
use \LINE\Clients\ChannelAccessToken\ApiException;
use \LINE\Clients\ChannelAccessToken\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChannelAccessTokenApiTest Class Doc Comment
 *
 * @category Class
 * @package  LINE\Clients\ChannelAccessToken
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelAccessTokenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getsAllValidChannelAccessTokenKeyIds
     *
     * .
     *
     */
    public function testGetsAllValidChannelAccessTokenKeyIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for issueChannelToken
     *
     * .
     *
     */
    public function testIssueChannelToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for issueChannelTokenByJWT
     *
     * .
     *
     */
    public function testIssueChannelTokenByJWT()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeChannelToken
     *
     * .
     *
     */
    public function testRevokeChannelToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeChannelTokenByJWT
     *
     * .
     *
     */
    public function testRevokeChannelTokenByJWT()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyChannelToken
     *
     * .
     *
     */
    public function testVerifyChannelToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyChannelTokenByJWT
     *
     * .
     *
     */
    public function testVerifyChannelTokenByJWT()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
