<?php
/**
 * Copyright 2025 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/**
 * LocationMessageContentTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LINE\Webhook\Test\Model;

use LINE\Webhook\Model\LocationMessageContent;
use PHPUnit\Framework\TestCase;

/**
 * LocationMessageContentTest Class Doc Comment
 *
 * @category    Class
 * @description LocationMessageContent
 * @package     LINE\Webhook
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LocationMessageContentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LocationMessageContent"
     */
    public function testLocationMessageContent()
    {
        $content = new LocationMessageContent();
        $this->assertInstanceOf(LocationMessageContent::class, $content);
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        $content = new LocationMessageContent();
        $title = 'Location Title';
        $content->setTitle($title);
        $this->assertEquals($title, $content->getTitle());
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
        $content = new LocationMessageContent();
        $address = '123 Main St, City';
        $content->setAddress($address);
        $this->assertEquals($address, $content->getAddress());
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
        $content = new LocationMessageContent();
        $latitude = 35.6581;
        $content->setLatitude($latitude);
        $this->assertEquals($latitude, $content->getLatitude());
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
        $content = new LocationMessageContent();
        $longitude = 139.7414;
        $content->setLongitude($longitude);
        $this->assertEquals($longitude, $content->getLongitude());
    }

    /**
     * Test attribute "markAsReadToken"
     */
    public function testPropertyMarkAsReadToken()
    {
        $content = new LocationMessageContent();
        $markAsReadToken = 'mark_as_read_token_123';
        $content->setMarkAsReadToken($markAsReadToken);
        $this->assertEquals($markAsReadToken, $content->getMarkAsReadToken());
    }
}
