<?php
/**
 * Copyright 2025 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/**
 * TextMessageContentTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LINE\Webhook\Test\Model;

use LINE\Webhook\Model\TextMessageContent;
use LINE\Webhook\Model\Emoji;
use LINE\Webhook\Model\Mention;
use PHPUnit\Framework\TestCase;

/**
 * TextMessageContentTest Class Doc Comment
 *
 * @category    Class
 * @description TextMessageContent
 * @package     LINE\Webhook
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TextMessageContentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TextMessageContent"
     */
    public function testTextMessageContent()
    {
        $content = new TextMessageContent();
        $this->assertInstanceOf(TextMessageContent::class, $content);
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
        $content = new TextMessageContent();
        $text = 'Hello, World!';
        $content->setText($text);
        $this->assertEquals($text, $content->getText());
    }

    /**
     * Test attribute "emojis"
     */
    public function testPropertyEmojis()
    {
        $content = new TextMessageContent();
        $emoji = new Emoji([
            'index' => 0,
            'length' => 5,
            'productId' => 'product123',
            'emojiId' => 'emoji456'
        ]);
        $content->setEmojis([$emoji]);
        $emojis = $content->getEmojis();
        $this->assertIsArray($emojis);
        $this->assertCount(1, $emojis);
        $this->assertInstanceOf(Emoji::class, $emojis[0]);
    }

    /**
     * Test attribute "mention"
     */
    public function testPropertyMention()
    {
        $content = new TextMessageContent();
        $mention = new Mention(['mentionees' => []]);
        $content->setMention($mention);
        $this->assertInstanceOf(Mention::class, $content->getMention());
    }

    /**
     * Test attribute "quoteToken"
     */
    public function testPropertyQuoteToken()
    {
        $content = new TextMessageContent();
        $quoteToken = 'quote_token_123';
        $content->setQuoteToken($quoteToken);
        $this->assertEquals($quoteToken, $content->getQuoteToken());
    }

    /**
     * Test attribute "quotedMessageId"
     */
    public function testPropertyQuotedMessageId()
    {
        $content = new TextMessageContent();
        $quotedMessageId = 'quoted_message_id_123';
        $content->setQuotedMessageId($quotedMessageId);
        $this->assertEquals($quotedMessageId, $content->getQuotedMessageId());
    }

    /**
     * Test attribute "markAsReadToken"
     */
    public function testPropertyMarkAsReadToken()
    {
        $content = new TextMessageContent();
        $markAsReadToken = 'mark_as_read_token_123';
        $content->setMarkAsReadToken($markAsReadToken);
        $this->assertEquals($markAsReadToken, $content->getMarkAsReadToken());
    }
}
