<?php
/**
 * VideoPlayCompleteEventTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LINE\Webhook\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VideoPlayCompleteEventTest Class Doc Comment
 *
 * @category    Class
 * @description Event for when a user finishes viewing a video at least once with the specified trackingId sent by the LINE Official Account.
 * @package     LINE\Webhook
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VideoPlayCompleteEventTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VideoPlayCompleteEvent"
     */
    public function testVideoPlayCompleteEvent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replyToken"
     */
    public function testPropertyReplyToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "videoPlayComplete"
     */
    public function testPropertyVideoPlayComplete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
