<?php
/**
 * Copyright 2024 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/**
 * PostbackAction
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\MessagingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LINE\Clients\MessagingApi\Model;
use \LINE\Clients\MessagingApi\ObjectSerializer;

/**
 * PostbackAction Class Doc Comment
 *
 * @category Class
 * @package  LINE\Clients\MessagingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostbackAction extends Action
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PostbackAction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'data' => 'string',
        'displayText' => 'string',
        'text' => 'string',
        'inputOption' => 'string',
        'fillInText' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'data' => null,
        'displayText' => null,
        'text' => null,
        'inputOption' => null,
        'fillInText' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'data' => false,
		'displayText' => false,
		'text' => false,
		'inputOption' => false,
		'fillInText' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'data' => 'data',
        'displayText' => 'displayText',
        'text' => 'text',
        'inputOption' => 'inputOption',
        'fillInText' => 'fillInText'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'data' => 'setData',
        'displayText' => 'setDisplayText',
        'text' => 'setText',
        'inputOption' => 'setInputOption',
        'fillInText' => 'setFillInText'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'data' => 'getData',
        'displayText' => 'getDisplayText',
        'text' => 'getText',
        'inputOption' => 'getInputOption',
        'fillInText' => 'getFillInText'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INPUT_OPTION_CLOSE_RICH_MENU = 'closeRichMenu';
    public const INPUT_OPTION_OPEN_RICH_MENU = 'openRichMenu';
    public const INPUT_OPTION_OPEN_KEYBOARD = 'openKeyboard';
    public const INPUT_OPTION_OPEN_VOICE = 'openVoice';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInputOptionAllowableValues()
    {
        return [
            self::INPUT_OPTION_CLOSE_RICH_MENU,
            self::INPUT_OPTION_OPEN_RICH_MENU,
            self::INPUT_OPTION_OPEN_KEYBOARD,
            self::INPUT_OPTION_OPEN_VOICE,
        ];
    }


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('displayText', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('inputOption', $data ?? [], null);
        $this->setIfExists('fillInText', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if (!is_null($this->container['data']) && (mb_strlen($this->container['data']) > 300)) {
            $invalidProperties[] = "invalid value for 'data', the character length must be smaller than or equal to 300.";
        }

        if (!is_null($this->container['data']) && (mb_strlen($this->container['data']) < 0)) {
            $invalidProperties[] = "invalid value for 'data', the character length must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getInputOptionAllowableValues();
        if (!is_null($this->container['inputOption']) && !in_array($this->container['inputOption'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'inputOption', must be one of '%s'",
                $this->container['inputOption'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets data
     *
     * @return string|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param string|null $data data
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            throw new \InvalidArgumentException('non-nullable data cannot be null');
        }
        if ((mb_strlen($data) > 300)) {
            throw new \InvalidArgumentException('invalid length for $data when calling PostbackAction., must be smaller than or equal to 300.');
        }
        if ((mb_strlen($data) < 0)) {
            throw new \InvalidArgumentException('invalid length for $data when calling PostbackAction., must be bigger than or equal to 0.');
        }

        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets displayText
     *
     * @return string|null
     */
    public function getDisplayText()
    {
        return $this->container['displayText'];
    }

    /**
     * Sets displayText
     *
     * @param string|null $displayText displayText
     *
     * @return self
     */
    public function setDisplayText($displayText)
    {
        if (is_null($displayText)) {
            throw new \InvalidArgumentException('non-nullable displayText cannot be null');
        }
        $this->container['displayText'] = $displayText;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text text
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets inputOption
     *
     * @return string|null
     */
    public function getInputOption()
    {
        return $this->container['inputOption'];
    }

    /**
     * Sets inputOption
     *
     * @param string|null $inputOption inputOption
     *
     * @return self
     */
    public function setInputOption($inputOption)
    {
        if (is_null($inputOption)) {
            throw new \InvalidArgumentException('non-nullable inputOption cannot be null');
        }
        $allowedValues = $this->getInputOptionAllowableValues();
        if (!in_array($inputOption, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'inputOption', must be one of '%s'",
                    $inputOption,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['inputOption'] = $inputOption;

        return $this;
    }

    /**
     * Gets fillInText
     *
     * @return string|null
     */
    public function getFillInText()
    {
        return $this->container['fillInText'];
    }

    /**
     * Sets fillInText
     *
     * @param string|null $fillInText fillInText
     *
     * @return self
     */
    public function setFillInText($fillInText)
    {
        if (is_null($fillInText)) {
            throw new \InvalidArgumentException('non-nullable fillInText cannot be null');
        }
        $this->container['fillInText'] = $fillInText;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


