<?php
/**
 * Copyright 2024 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/**
 * SubscribedMembershipUser
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\MessagingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LINE\Clients\MessagingApi\Model;

use \ArrayAccess;
use \LINE\Clients\MessagingApi\ObjectSerializer;

/**
 * SubscribedMembershipUser Class Doc Comment
 *
 * @category Class
 * @description Object containing user membership subscription information.
 * @package  LINE\Clients\MessagingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SubscribedMembershipUser implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SubscribedMembershipUser';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'membershipNo' => 'int',
        'joinedTime' => 'int',
        'nextBillingDate' => 'string',
        'totalSubscriptionMonths' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'membershipNo' => null,
        'joinedTime' => null,
        'nextBillingDate' => null,
        'totalSubscriptionMonths' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'membershipNo' => false,
		'joinedTime' => false,
		'nextBillingDate' => false,
		'totalSubscriptionMonths' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'membershipNo' => 'membershipNo',
        'joinedTime' => 'joinedTime',
        'nextBillingDate' => 'nextBillingDate',
        'totalSubscriptionMonths' => 'totalSubscriptionMonths'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'membershipNo' => 'setMembershipNo',
        'joinedTime' => 'setJoinedTime',
        'nextBillingDate' => 'setNextBillingDate',
        'totalSubscriptionMonths' => 'setTotalSubscriptionMonths'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'membershipNo' => 'getMembershipNo',
        'joinedTime' => 'getJoinedTime',
        'nextBillingDate' => 'getNextBillingDate',
        'totalSubscriptionMonths' => 'getTotalSubscriptionMonths'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('membershipNo', $data ?? [], null);
        $this->setIfExists('joinedTime', $data ?? [], null);
        $this->setIfExists('nextBillingDate', $data ?? [], null);
        $this->setIfExists('totalSubscriptionMonths', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['membershipNo'] === null) {
            $invalidProperties[] = "'membershipNo' can't be null";
        }
        if ($this->container['joinedTime'] === null) {
            $invalidProperties[] = "'joinedTime' can't be null";
        }
        if ($this->container['nextBillingDate'] === null) {
            $invalidProperties[] = "'nextBillingDate' can't be null";
        }
        if ($this->container['totalSubscriptionMonths'] === null) {
            $invalidProperties[] = "'totalSubscriptionMonths' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets membershipNo
     *
     * @return int
     */
    public function getMembershipNo()
    {
        return $this->container['membershipNo'];
    }

    /**
     * Sets membershipNo
     *
     * @param int $membershipNo The user's member number in the membership plan.
     *
     * @return self
     */
    public function setMembershipNo($membershipNo)
    {
        if (is_null($membershipNo)) {
            throw new \InvalidArgumentException('non-nullable membershipNo cannot be null');
        }
        $this->container['membershipNo'] = $membershipNo;

        return $this;
    }

    /**
     * Gets joinedTime
     *
     * @return int
     */
    public function getJoinedTime()
    {
        return $this->container['joinedTime'];
    }

    /**
     * Sets joinedTime
     *
     * @param int $joinedTime UNIX timestamp at which the user subscribed to the membership.
     *
     * @return self
     */
    public function setJoinedTime($joinedTime)
    {
        if (is_null($joinedTime)) {
            throw new \InvalidArgumentException('non-nullable joinedTime cannot be null');
        }
        $this->container['joinedTime'] = $joinedTime;

        return $this;
    }

    /**
     * Gets nextBillingDate
     *
     * @return string
     */
    public function getNextBillingDate()
    {
        return $this->container['nextBillingDate'];
    }

    /**
     * Sets nextBillingDate
     *
     * @param string $nextBillingDate Next payment date for membership plan. - Format: yyyy-MM-dd (e.g. 2024-02-08) - Timezone: UTC+9
     *
     * @return self
     */
    public function setNextBillingDate($nextBillingDate)
    {
        if (is_null($nextBillingDate)) {
            throw new \InvalidArgumentException('non-nullable nextBillingDate cannot be null');
        }
        $this->container['nextBillingDate'] = $nextBillingDate;

        return $this;
    }

    /**
     * Gets totalSubscriptionMonths
     *
     * @return int
     */
    public function getTotalSubscriptionMonths()
    {
        return $this->container['totalSubscriptionMonths'];
    }

    /**
     * Sets totalSubscriptionMonths
     *
     * @param int $totalSubscriptionMonths The period of time in months that the user has been subscribed to a membership plan. If a user previously canceled and then re-subscribed to the same membership plan, only the period after the re-subscription will be counted.
     *
     * @return self
     */
    public function setTotalSubscriptionMonths($totalSubscriptionMonths)
    {
        if (is_null($totalSubscriptionMonths)) {
            throw new \InvalidArgumentException('non-nullable totalSubscriptionMonths cannot be null');
        }
        $this->container['totalSubscriptionMonths'] = $totalSubscriptionMonths;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


