<?php
/**
 * LiffApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\Liff
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LINE\Clients\Liff\Test\Api;

use \LINE\Clients\Liff\Configuration;
use \LINE\Clients\Liff\ApiException;
use \LINE\Clients\Liff\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LiffApiTest Class Doc Comment
 *
 * @category Class
 * @package  LINE\Clients\Liff
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LiffApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for liffV1AppsGet
     *
     * Get all LIFF apps.
     *
     */
    public function testLiffV1AppsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for liffV1AppsLiffIdDelete
     *
     * Delete LIFF app from a channel.
     *
     */
    public function testLiffV1AppsLiffIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for liffV1AppsLiffIdPut
     *
     * .
     *
     */
    public function testLiffV1AppsLiffIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for liffV1AppsPost
     *
     * .
     *
     */
    public function testLiffV1AppsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
