<?php
/**
 * GetStatisticsPerUnitResponseOverviewTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\Insight
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LINE\Clients\Insight\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetStatisticsPerUnitResponseOverviewTest Class Doc Comment
 *
 * @category    Class
 * @description Statistics related to messages.
 * @package     LINE\Clients\Insight
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetStatisticsPerUnitResponseOverviewTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetStatisticsPerUnitResponseOverview"
     */
    public function testGetStatisticsPerUnitResponseOverview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uniqueImpression"
     */
    public function testPropertyUniqueImpression()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uniqueClick"
     */
    public function testPropertyUniqueClick()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uniqueMediaPlayed"
     */
    public function testPropertyUniqueMediaPlayed()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uniqueMediaPlayed100Percent"
     */
    public function testPropertyUniqueMediaPlayed100Percent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
