name: PHP Checks

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  tests:
    name: Run checks on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        php: 
          - 8.2
          - 8.3
          - 8.4
          - 8.5
        include:
          - php: 8.2
            analysis: true
          - php: 8.3
            analysis: true
          - php: 8.4
            analysis: true
          - php: 8.5
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate code
        run: python generate-code.py

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Check copyrights
        if: matrix.analysis
        run: composer copyright

      - name: Check code style with PHP_CodeSniffer
        if: matrix.analysis
        run: composer cs

      - name: Check with PHP Mess Detector 
        if: matrix.analysis
        run: composer md

      - name: Check with PHPStan
        if: matrix.analysis
        run: composer stan

      - name: Run unit tests
        if: matrix.analysis
        run: composer test

  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@cf51507d80d4d6522a07348e3d58790290eaf0b6 # v2.0.0
        with:
          skip_push: "true"
