<?php
/**
 * AddAudienceToAudienceGroupRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LINE\Clients\ManageAudience
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LINE\Clients\ManageAudience\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AddAudienceToAudienceGroupRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by JSON)
 * @package     LINE\Clients\ManageAudience
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddAudienceToAudienceGroupRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddAudienceToAudienceGroupRequest"
     */
    public function testAddAudienceToAudienceGroupRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "audienceGroupId"
     */
    public function testPropertyAudienceGroupId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uploadDescription"
     */
    public function testPropertyUploadDescription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "audiences"
     */
    public function testPropertyAudiences()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
